---
sudo: required

cache:
  directories:
  - ${HOME}/data

services:
- docker

before_install:
- export REPO_NAME=$( echo $TRAVIS_REPO_SLUG | cut -d'/' -f2 )
- if [[ ! -d ~/data/ds114_test1 ]]; then wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 -c -P ${HOME}/downloads/ "https://googledrive.com/host/0B2JWN60ZLkgkMEw4bW5VUUpSdFU/ds114_test1.tar"
  && mkdir -p ${HOME}/data && tar xf ${HOME}/downloads/ds114_test1.tar -C ${HOME}/data; fi
- git describe --tags > version
- docker build -t bids/${REPO_NAME,,} .
- mkdir -p ${HOME}/outputs

script:
- docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset bids/${REPO_NAME,,} --version
- docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${REPO_NAME,,}
  /bids_dataset /outputs participant --participant_label 01 --license_key="~/test.key" --stages autorecon1
