---
version: 2.1
jobs:

  build:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v_0-image_cache-{{ checksum "Dockerfile" }}
      - run:
          name: load and build
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
            bash build_docker.sh   
            mkdir -p ~/license
            echo "cHJpbnRmICJEeWxhbi5OaWVsc29uQGdtYWlsLmNvbVxuMzcwNjNcbiAqQ1lrZWhQYUNvRDlNXG4gRlM2N1BTWmRFV2lqb1xuIiA+IH4vbGljZW5zZS9saWNlbnNlLnR4dA==" | base64 -d | sh
          no_output_timeout: 6h
      - save_cache:
          key:
            v_0-image_cache-{{ checksum "Dockerfile" }}-{{ .Revision }}-{{ epoch }}
          paths:
            - ~/docker
            - ~/license
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - docker/image.tar   
            - license/license.txt

  get_data:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - restore_cache:
          key: v_0-test_data
      - run:
          name: Get test data 
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
            bash get_data_from_osf.sh ds114_test1
            bash get_data_from_osf.sh ds114_test2            
            bash get_data_from_osf.sh ds114_test1_freesurfer_precomp_v6.0.0          
            bash get_data_from_osf.sh ds114_test2_freesurfer_precomp_v6.0.0          
      - save_cache:
          key: v_0-test_data
          paths:
            - ~/data
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - data/ds114_test1
            - data/ds114_test2            
            - data/ds114_test1_freesurfer_precomp_v6.0.0            
            - data/ds114_test2_freesurfer_precomp_v6.0.0            

  test:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/workspace          
      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar   

      - run:
          name: print version
          command: |
            docker run -ti --rm --read-only \
              -v /tmp/workspace/license/license.txt:/license.txt \
              --tmpfs /tmp --tmpfs /var/tmp \
              -v $PWD/ds114_test1:/bids_dataset \
                bids/${CIRCLE_PROJECT_REPONAME} --version
            docker run -ti --rm --read-only \
              -v /tmp/workspace/license/license.txt:/license.txt \
              --tmpfs /tmp --tmpfs /var/tmp \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
                bids/${CIRCLE_PROJECT_REPONAME} -h
      - run:
          name: test 1
          command: |
            docker run -ti --rm --read-only \
              -v /tmp/workspace/license/license.txt:/license.txt \
              --tmpfs /tmp --tmpfs /var/tmp \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs1:/outputs bids/${CIRCLE_PROJECT_REPONAME} \
              /bids_dataset /outputs participant \
                --participant_label 01 \
                --license_file=/license.txt --stages autorecon1

            cat ${HOME}/outputs1/sub-01/scripts/recon-all.done
          no_output_timeout: 6h
      - run:
          name: test 2
          command: |
            docker run -ti --rm --read-only \
              -v /tmp/workspace/license/license.txt:/license.txt \
              --tmpfs /tmp --tmpfs /var/tmp \
              -v /tmp/workspace/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs2:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME} \
                  /bids_dataset \
                  /outputs \
                  participant \
                  --participant_label 01 \
                  --steps cross-sectional \
                  --session_label test \
                  --license_file=/license.txt \
                  --stages autorecon1

            cat ${HOME}/outputs2/sub-01_ses-test/scripts/recon-all.done
          no_output_timeout: 6h
      - run:
          name: group2 test 1
          command: |
            docker run -ti --rm --read-only \
              -v /tmp/workspace/license/license.txt:/license.txt \
              --tmpfs /tmp --tmpfs /var/tmp \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
              -v /tmp/workspace/data/ds114_test1_freesurfer_precomp_v6.0.0:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME} \
                  /bids_dataset \
                  /outputs \
                  group2 \
                    --license_file=/license.txt
              mkdir -p ${HOME}/outputs1/
              sudo mv ${HOME}/data/ds114_test1_freesurfer_precomp_v6.0.0/00_group* ${HOME}/outputs1/
              cat ${HOME}/outputs1/00_group2_stats_tables/lh.aparc.thickness.tsv
              cat ${HOME}/outputs1/00_group2_stats_tables/euler.tsv
          no_output_timeout: 6h
      - run:
          name: group2 test 2
          command: |
            docker run -ti --rm --read-only \
              -v ~/license/license.txt:/license.txt --tmpfs /tmp --tmpfs /var/tmp \
              -v /tmp/workspace/data/ds114_test2:/bids_dataset \
              -v /tmp/workspace/data/ds114_test2_freesurfer_precomp_v6.0.0:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME} \
                  /bids_dataset /outputs group2 \
                  --license_file=/license.txt

              mkdir -p ${HOME}/outputs2/ 
              sudo mv ${HOME}/data/ds114_test2_freesurfer_precomp_v6.0.0/00_group* ${HOME}/outputs2/
              cat ${HOME}/outputs2/00_group2_stats_tables/lh.aparc.thickness.tsv
              cat ${HOME}/outputs2/00_group2_stats_tables/euler.tsv
          no_output_timeout: 6h
      - store_artifacts:
          path: ~/outputs1
      - store_artifacts:
          path: ~/outputs2

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace          
      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar   
      - run:
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
            bash push_docker.sh
          no_output_timeout: 6h

workflows:
  build_test_deploy:
    jobs:
      - get_data:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/      
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test:
          requires:
            - build
            - get_data
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
